services:
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: mongo:7
    ports:
      - "27017:27017"
    env_file:
      - mongo.env
    volumes:
      - ./db:/data/db
